### ISSUE TITLE
Issue submitting first question

### ISSUE THREAD

**Issue by noelfarris** [TIY-Austin-Front-End-Engineering/Iron-Quizzes#179]
Cannot submit the first question, have to submit multiple times before moving to the second question. This only happens on the first question. Could be a loading issue.

**Comment by jstitts** [comment]
Tested this a whole bunch and it looks like it is just a loading issue. 

> created multiple new quizzes and yes the first question takes a bit to load but was populated in about 5 seconds.
> after the first question all others seen to pop up within a second
