### ISSUE TITLE
Add credits page

### ISSUE THREAD

**Issue by alarner** [TIY-Austin-Front-End-Engineering/Iron-Quizzes#204]
We should add a page to credit all of the people who helped us with this project including the designers and all of the team members. Create a page to list our names and links to github / twitter / linkedIn / portfolios for each of the team members and designers. If you get extra time, add head shots for each team member.

**Comment by m2mathew** [comment]
I have sent the design cohort a message on slack to ask for their GitHub repo links and other portfolio/website links.

**Comment by m2mathew** [comment]
Added a footer to hold a link to The Iron Yard and the CreditsComponent. 

Added all students/instructors from both front-end and design cohorts.
